### ISSUE TITLE
Async as reserved keyword in python3

### ISSUE THREAD

**Issue by ktk-sdk** [FlatIO/api-client-python#2]
Whenever I import this api it always gets me this error:

```
Traceback (most recent call last):
  File "flat_counterpoint.py", line 1, in <module>
    import flat_api
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flat_api/__init__.py", line 19, in <module>
    from flat_api.api.account_api import AccountApi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flat_api/api/__init__.py", line 6, in <module>
    from flat_api.api.account_api import AccountApi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flat_api/api/account_api.py", line 121
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

Correct me if I'm wrong, but I think this might be due to async being a reserved keyword in python 3.7.

**Comment by gierschv** [comment]
Thanks for your feedback @ktparkk, I'm checking that today

**Comment by gierschv** [comment]
Fixed on master, I will release a new version shortly.

**Comment by ktk-sdk** [comment]
Thanks @gierschv !

**Comment by gierschv** [comment]
I just release the version v0.7.0 & uploaded to [PyPI](https://pypi.org/project/flat-api/).

Please let me know if this works for you or need anything else.
Cheers,
Vince

**Comment by ktk-sdk** [comment]
Seems to work perfect now!

Thank you,
Katie Park
